---
keystone_server: 10.4.1.5
keystone_server_internal_ip: 10.4.1.5

keystone_user: keystone
keystone_db_password: keysarelocked
glance_user: glance
glance_db_password: keysarelocked
quantum_user: quantum
quantum_db_password: keysarelocked
nova_user: nova
nova_db_password: keysarelocked
cinder_user: cinder
cinder_db_password: keysarelocked

admin_token: 012345SECRET99TOKEN012345
